language: cpp

addons_shortcuts:
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.8' ]
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.9' ]
  addons_gcc5: &gcc5
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-5' ]
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-6' ]

matrix:
  include:
  - os: linux
    compiler: clang
    env: COMPILER=clang++
  - os: linux
    compiler: "gcc-4.8"
    env: COMPILER=g++-4.8
    addons: *gcc48
  - os: linux
    compiler: "gcc-4.9"
    env: COMPILER=g++-4.9
    addons: *gcc49
  - os: linux
    compiler: "gcc-5"
    env: COMPILER=g++-5
    addons: *gcc5
  - os: linux
    compiler: "gcc-6"
    env: COMPILER=g++-6
    addons: *gcc6

install:
  - export CXX="$COMPILER"
  - $CXX --version

#before_script:
#  - "./autogen.sh"
#  - "./configure"

script:
  - make
  - make check

notifications:
  on_success: change
  on_failure: always
