language: cpp
dist: trusty
sudo: required
compiler: clang

os:
- linux

sources:
- ubuntu-toolchain-r-test

packages:
- g++-4.8
- g++-4.9
- g++-5
- g++-6

env:
- COMPILER=g++-4.8
- COMPILER=g++-4.9
- COMPILER=g++-5
- COMPILER=g++-6
- COMPILER=clang++

install:
  - export CXX="$COMPILER"
  - $CXX --version

#before_script:
#  - "./autogen.sh"
#  - "./configure"

script:
  - make
  - make check

notifications:
  on_success: change
  on_failure: always
