language: cpp
dist: trusty

addons_shortcuts:
  addons_clang: &clangdef
    apt:
      sources:
      packages: [ 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.8', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.9', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc5: &gcc5
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-5', 'autoconf-archive', 'libgmp-dev' ]
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-6', 'autoconf-archive', 'libgmp-dev' ]

matrix:
  include:
  - os: linux
    compiler: clang
    env: COMPILER=clang++
    addons: *clangdef
  - os: linux
    compiler: "gcc-4.8"
    env: COMPILER=g++-4.8
    addons: *gcc48
  - os: linux
    compiler: "gcc-4.9"
    env: COMPILER=g++-4.9
    addons: *gcc49
  - os: linux
    compiler: "gcc-5"
    env: COMPILER=g++-5
    addons: *gcc5
  - os: linux
    compiler: "gcc-6"
    env: COMPILER=g++-6
    addons: *gcc6

install:
  - export CXX="$COMPILER"
  - $CXX --version
  - autoconf --version
  - git clone https://github.com/nauotit/openf4 && cd openf4 && autoreconf --install && ./configure --prefix=$HOME/local && make && make install && export OPENF4DIR=$HOME/local

before_script:
  - autoreconf --install
  - ./configure

script:
  - make
  - make check

notifications:
  on_success: change
  on_failure: always
