language: cpp
dist: trusty

addons_shortcuts:
  addons_clang: &clangdef
    apt:
      sources:
      packages: [ 'libgmp-dev' ]
  addons_gcc48: &gcc48
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.8', 'libgmp-dev' ]
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-4.9', 'libgmp-dev' ]
  addons_gcc5: &gcc5
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-5', 'libgmp-dev' ]
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-6', 'libgmp-dev' ]
  addons_gcc7: &gcc7
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: [ 'g++-7', 'libgmp-dev' ]

matrix:
  include:
  - os: linux
    compiler: clang
    env: COMPILER=clang++
    addons: *clangdef
  - os: linux
    compiler: "gcc-4.8"
    env: COMPILER=g++-4.8
    addons: *gcc48
  - os: linux
    compiler: "gcc-4.9"
    env: COMPILER=g++-4.9
    addons: *gcc49
  - os: linux
    compiler: "gcc-5"
    env: COMPILER=g++-5
    addons: *gcc5
  - os: linux
    compiler: "gcc-6"
    env: COMPILER=g++-6
    addons: *gcc6
  - os: linux
    compiler: "gcc-7"
    env: COMPILER=g++-7
    addons: *gcc7

install:
  - export CXX="$COMPILER"
  - $CXX --version
  - autoconf --version

script:
  - ./install_openf4.sh
  - autoreconf --install
  - ./configure
  - make MAXVARS=16 FIELDSIZE=256 m4gb openf4
  - make MAXVARS=16 FIELDSIZE=31 m4gb openf4
  - make check

notifications:
  on_success: change
  on_failure: always
